### ISSUE TITLE
2016 Image Testing TODO

### ISSUE THREAD

**Issue by ThadHouse** [robotdotnet/WPILib#81]
- [x] Test Status Check Bug
- [x] Test Notifier Bug (Looks fixed. Need merge before final check)
- [x] Test needing to initialize a digital port before calling notifier. (Looks fixed. Need merge before final check)
- [x] Test ADXL345 (I2C)
- [x] Test ADXL345 (SPI)
  ~~Test Analog Accelerometer~~ Don't have one.
- [x] Test NavX MXP
- [x] Test Analog Gyro
- [x] Test Encoders
- [x] Test PDP
- [x] Test PCM
- [x] Test Analog Ultrasonic
- [x] Test Servo
- [ ] More Testing on NetworkTablesCore
- [ ] Test Native Camera Server (If I can get access to a USB camera)
- [x] ~~Figure out why the robot code stopping causes the robot start script to run in an infinite loop~~ Changes by FIRST cause this, and its now the proper usage.

That should be everything I need to do, and its everything I can do with the parts I have on hand. I might be able to get access to some Talon SRX's, but thats still an unknown at this point. If anybody else has anything they want me to test before kickoff 2016, if you send me code, or if it needs specific hardware mail me the hardware, and I'll get it done.

**Comment by ThadHouse** [comment]
I've been testing this for the past few weeks now, and everything I've tested has been working. Closing
